language: java
jkd:
  -openjdk8

branches:
  only:
    -master

# Travis 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - yh9638@skuniv.ac.kr